name: passwordmanager
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1
environment:
  sdk: ">=2.17.6 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  animated_splash_screen: ^1.3.0
  dropdown_textfield: ^1.0.5
  fluttertoast: ^8.1.1
  dropdown_button2: ^1.8.5
  sqflite: ^2.0.3+1
  path: ^1.8.1
  encrypt: ^5.0.1
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true
  assets:
    - images/
    - images/logo/
